<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var \Magefan\HtmlSitemap\Block\Link $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$config = $objectManager->create(\Magefan\HtmlSitemap\Model\Config::class);
$displayInArray = explode(',', $config->displayIn());
$openLinks = ($block->getOpenLinks() == 1) ? '' : 'target="_blank"';
?>
<?php if ($config->isEnabled()): ?>
    <?php if (in_array('2', $displayInArray)): ?>
    <li>
        <a href="<?= $escaper->escapeUrl($block->getHref()) ?>"
           name="footer_htmlsitemap_link" <?= $openLinks ?>>
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
    <?php endif ?>
<?php endif ?>