<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

use Magefan\HtmlSitemap\Block\Link;
use Magento\Framework\Escaper;

/** @var Link $block */
/** @var Escaper $escaper */

$openLinks = $block->getOpenLinks() == 1 ? '' : 'target="_blank"';
?>
<?php if ($block->canShowSitemapLink()): ?>
    <li>
        <a href="<?= $escaper->escapeUrl($block->getHref()) ?>" name="header_htmlsitemap_link" <?= $openLinks ?>>
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif ?>
