<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var \Magefan\HtmlSitemap\Block\Link $block
 * @var \Magento\Framework\Escaper $escaper
 */

$openLinks = $block->getOpenLinks() == 1 ? '' : 'target="_blank"';
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php if ($block->canShowSitemapLink()): ?>
    <li>
        <a href="<?= $escaper->escapeUrl($block->getHref()) ?>" name="header_htmlsitemap_link" <?= $openLinks ?>>
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif ?>
