<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magefan\HtmlSitemap\Block\Blog\Category
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <br>
    <?php $items = $block->getCollection(); ?>

    <?php if (count($items)) { ?>

        <div class="widget block block-categories" data-bind="scope: 'categories'">
            <div class="accordion"  id="accordion-2">
                <?php
                $level = 0;
                $first = true;
                foreach ($items as $item) {
                    $newLevel = $item->getLevel();
                    if ($level == $newLevel && !$first) {
                        echo '</li>';
                    }
                    if ($level < $newLevel) {
                        echo '<ul>';
                    }
                    if ($level > $newLevel) {
                        for ($i = $level; $i > $newLevel; $i--) {
                            echo '</ul></li>';
                        }
                    }
                    ?>
                    <li>
                    <a href="<?= $block->escapeUrl($item->getCategoryUrl()) ?>" title="<?= $block->escapeHtml($item->getTitle()) ?>">
                        <?= $block->escapeHtml($item->getTitle()) ?>
                    </a>
                    <?php
                    $level = $newLevel;
                    $first = false;
                }

                $closedTags = ($level > 0) ? $level - 1 : 1;
                echo str_repeat('</li></ul>', $closedTags);
                ?>
            </div>
        </div>
        <style>
            .htmlsitemap-blog_category-categories .widget.block-categories ul li {
                padding: 0 0 0 15px;
            }
        </style>
    <?php } ?>
</div>


