<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magefan\HtmlSitemap\Block\Blog\Post
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <h2><?= $block->escapeHtml(__('All Posts')) ?></h2>
    <br>
    <?php
    $lettersArray = range('A', 'Z');
    $lettersArray[] = '#';
    $postCollection = $block->getAllPostCollection();

    foreach ($lettersArray as $letter):
        $postsArray = [];
         foreach ($postCollection as $post) {
            if (mb_strtoupper(substr($post->getTitle(), 0, 1)) == $letter || $letter == '#') {
                $postsArray[] = ['name' => $post->getTitle(), 'url' => $post->getPostUrl()];
                $postCollection->removeItemByKey($post->getId());
            }
        }

        if (!$postsArray) {
            continue;
        }
        ?>

    <div class="sitemap-item-section">
        <p>
            <strong><?= $block->escapeHtml($letter); ?></strong>
        </p>

        <?php
            $ulLimit = ceil(count($postsArray)/4);
            $liCount = 0;
            $i = 0;
        ?>
        <table>
            <tr>
                <?php foreach ($postsArray as $post) {
                    if ($liCount == 0) { ?>
                        <th>
                        <ul style="list-style-type:none">
                    <?php } ?>
                        <li>
                            <a href="<?= $block->escapeUrl($post['url']) ?>">
                                <?= $block->escapeHtml($post['name']) ?>
                            </a>
                        </li>
                    <?php
                    $liCount++;
                    $i++;
                    if ($liCount == $ulLimit || $i == count($postsArray)) { ?>
                        </ul>
                        </th>
                        <?php $liCount = 0; ?>
                    <?php } ?>
                <?php } ?>
            </tr>
        </table>
    </div>
    <?php endforeach; ?>
</div>
