<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magefan\HtmlSitemap\Block\Blog\Post
 */
?>
<div class="sitemap-item-type sitemap-item-section">

    <?php
    $lettersArray = range('A', 'Z');
    $lettersArray[] = '#';
    $postCollection = $block->getAllPostCollection();

    foreach ($lettersArray as $letter):
        $postsArray = [];
         foreach ($postCollection as $post) {
            if (mb_strtoupper(substr($post->getTitle(), 0, 1)) == $letter || $letter == '#') {
                $postsArray[] = ['name' => $post->getTitle(), 'url' => $post->getPostUrl()];
                $postCollection->removeItemByKey($post->getId());
            }
        }

        if (!$postsArray) {
            continue;
        }
        ?>

    <div class="sitemap-item-section">
        <p>
            <strong><?= $block->escapeHtml($letter); ?></strong>
        </p>

        <div class="sitemap-item-wrap">
            <?php foreach ($postsArray as $post): ?>
                <a class="sitemap-item" href="<?= $block->escapeUrl($post['url']) ?>" title="<?= $block->escapeHtml($post['name']) ?>">
                    <?= $block->escapeHtml($post['name']) ?>
                </a>
            <?php endforeach; ?>
        </div>

    </div>
    <?php endforeach; ?>
</div>
