<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magefan\HtmlSitemap\Block\Blog\Post
 */
?>
<div class="sitemap-item-type">
    <h2><?= $block->escapeHtml(__('All Posts')) ?></h2>
    <br />
    <?php $lettersArray = range('A', 'Z');
    $postCollection = $block->getAllPostCollection();
    foreach ($lettersArray as $letter):
        $postsArray = [];?>
        <?php foreach ($postCollection as $post):
            if (substr($post->getTitle(), 0, 1) == $letter):
                $postsArray[] = ['name' => $post->getTitle(), 'url' => $post->getPostUrl()];
                $postCollection->removeItemByKey($post->getEntityId());
            endif;
        endforeach;?>
        <?php if ($postsArray):?>
            <p><strong><?= $block->escapeHtml($letter); ?></strong></p>
        <?php endif;?>
        <?php $ulLimit = ceil(count($postsArray)/4);
        $liCount = 0; ?>
        <table>
            <th>
                <?php foreach ($postsArray as $post):
                    if ($liCount == 0): ?>
                        <th>
                        <ul style="list-style-type:none">
                    <?php endif; ?>
                        <li>
                            <a href="<?= $block->escapeUrl($post['url']) ?>">
                                <?= $block->escapeHtml($post['name']) ?>
                            </a>
                        </li>
                    <?php
                    $liCount ++;
                    if ($liCount == $ulLimit): ?>
                        </ul>
                        </th>
                        <?php $liCount = 0; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
                </th>
            </tr>
        </table>
    <?php endforeach; ?>
</div>
