<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
declare(strict_types=1);

namespace Magefan\HtmlSitemap\Block\Blog;

use Magefan\HtmlSitemap\Model\Config;
use Magento\Framework\View\Element\Template;
use Magefan\HtmlSitemap\Model\BlogFactory;

abstract class AbstractCategories extends Template
{
    const XML_PATH_TO_BLOG_CATEGORY_TITLE = 'mfhs/blogcategorylinks/title';
    const XML_PATH_TO_BLOG_CATEGORY_DEPTH = 'mfhs/blogcategorylinks/maxdepth';
    const XML_PATH_TO_BLOG_CATEGORY_VIEW_MORE = 'mfhs/blogcategorylinks/displaymore';
    const XML_PATH_TO_BLOG_CATEGORY_LIMIT = 'mfhs/blogcategorylinks/maxnumberlinks';

    /**
     * @var Config
     */
    protected $config;

    /**
     * @var BlogFactory
     */
    protected $blogFactory;

    /**
     * Category constructor.
     * @param Template\Context $context
     * @param Config $config
     * @param BlogFactory $blogFactory
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        Config $config,
        BlogFactory $blogFactory,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->config = $config;
        $this->blogFactory = $blogFactory;
    }

    /**
     * @return string
     */
    public function getBlockTitle()
    {
        return (string)$this->config->getConfig(self::XML_PATH_TO_BLOG_CATEGORY_TITLE);
    }

    public function getCollection()
    {
        $k = 'collection';
        if (!$this->hasData($k)) {
            $items = $this->blogFactory->createCategoryCollection()
                ->addActiveFilter()
                ->addStoreFilter($this->_storeManager->getStore()->getId());
            if ($ignoredLinks = $this->config->getIgnoredLinks()) {
                $items->addFieldToFilter('identifier', ['nin' => $ignoredLinks]);
            }

            $items = $items->addFieldToFilter('mf_exclude_html_sitemap', 0)
                ->setOrder('position')
                ->getTreeOrderedArray();

            if ($pageSize = $this->getPageSize()) {
                $items = array_slice($items, 0, $pageSize);
            }

            foreach ($items as $key => $item) {
                if ($maxDepth = $this->getMaxDepth()) {
                    if ($maxDepth > 0 && $item->getLevel() >= $maxDepth) {
                        unset($items[$key]);
                    }
                }
            }

            $this->setData($k, $items);
        }

        return $this->getData($k);
    }

    /**
     * @return int
     */
    protected function getPageSize(): int
    {
        return 0;
    }

    /**
     * @return int
     */
    protected function getMaxDepth(): int
    {
        return 0;
    }

    /**
     * @return string
     */
    public function toHtml()
    {
        if (!$this->config->isBlogEnabled()) {
            return '';
        }
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}
