<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
declare(strict_types=1);

namespace Magefan\HtmlSitemap\Block\Blog;

use Magento\Framework\DataObject;
use Magento\Framework\View\Element\Template;
use Magefan\HtmlSitemap\Model\Config;
use Magefan\HtmlSitemap\Model\BlogFactory;

abstract class AbstractPosts extends Template
{
    const XML_PATH_TO_BLOG_POST_TITLE = 'mfhs/blogpostlinks/title';
    const XML_PATH_TO_BLOG_POSTS_LIMIT = 'mfhs/blogpostlinks/maxnumberlinks';
    const XML_PATH_TO_BLOG_POST_VIEW_MORE = 'mfhs/blogcategorylinks/displaymore';

    /**
     * @var Config
     */
    protected $config;

    /**
     * @var BlogFactory
     */
    protected $blogFactory;

    /**
     * Post constructor.
     * @param Template\Context $context
     * @param Config $config
     * @param BlogFactory $blogFactory
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        Config $config,
        BlogFactory $blogFactory,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->config = $config;
        $this->blogFactory = $blogFactory;
    }

    /**
     * @return string
     */
    public function getBlockTitle()
    {
        return (string)$this->config->getConfig(self::XML_PATH_TO_BLOG_POST_TITLE);
    }

    /**
     * @return mixed
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function getCollection()
    {
        $k = 'collection';
        if (null === $this->getData($k)) {
            $items = $this->blogFactory->createPostCollection()
                ->addActiveFilter()
                ->addStoreFilter($this->_storeManager->getStore()->getId())
                ->addFieldToFilter('mf_exclude_html_sitemap', 0);

            if ($ignoredLinks = $this->config->getIgnoredLinks()) {
                $items->addFieldToFilter('identifier', ['nin' => $ignoredLinks]);
            }

            if ($pageSize = $this->getPageSize()) {
                $items->setPageSize($pageSize);
            }
            $this->setData($k, $items);
        }

        return $this->getData($k);
    }

    /**
     * @return mixed
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function getItems()
    {
        $k = 'items';
        if (null === $this->getData($k)) {
            $items = [];
            foreach ($this->getCollection() as $collectionItem) {
                $item = new DataObject([
                    'url' => $collectionItem->getPostUrl(),
                    'name' => $collectionItem->getTitle(),
                    'object' => $collectionItem
                ]);
                $items[] = $item;
            }
            $this->setData($k, $items);
        }

        return $this->getData($k);
    }


    /**
     * @return int
     */
    protected function getPageSize(): int
    {
        return 0;
    }

    /**
     * @return string
     */
    public function toHtml()
    {
        if (!$this->config->isBlogEnabled()) {
            return '';
        }
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}