<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Index\Blog\Posts $block
 */

$posts = $block->getItems();
?>

<?php if (count($posts)) { ?>
<div class="sitemap-item-type sitemap-item-section">
    <h2 class="sitemap-title"><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
    <div class="sitemap-item-wrap">
    <?php foreach ($posts as $post): ?>
        <a class="sitemap-item" href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getName()) ?>">
            <?= $block->escapeHtml($post->getName()) ?>
        </a>
    <?php endforeach; ?>
    </div>
    <?php if ($block->showViewMore()): ?>
        <a class="view-more" href="<?= $block->escapeUrl($block->getUrl('*/blog/posts'))?>">
            <?= $block->escapeHtml(__('View more'))?>
        </a>
    <?php endif; ?>
</div>
<?php } ?>
