<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magefan\HtmlSitemap\Block\Catalog\Product
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <h2><?=$block->escapeHtml(__('All Products')) ?></h2>
    <br>
    <?php
    $lettersArray = range('A', 'Z');
    $lettersArray[] = '#';
    $productCollection = $block->getAllProductCollection();

    foreach ($lettersArray as $letter) {
        $productsArray = [];
         foreach ($productCollection as $product) {
            if (mb_strtoupper(substr($product->getName(), 0, 1)) == $letter || $letter == '#') {
                $productsArray[] = ['name' => $product->getName(), 'url' => $product->getProductUrl()];
                $productCollection->removeItemByKey($product->getEntityId());
            }
        }

        if (!$productsArray) {
            continue;
        }
        ?>

        <div class="sitemap-item-section">
            <p>
                <strong><?= $block->escapeHtml($letter); ?></strong>
            </p>

            <?php
                $ulLimit = ceil(count($productsArray)/4);
                $liCount = 0;
                $i = 0;
            ?>
            <table>
                <tr>
                <?php foreach ($productsArray as $product) {
                    if ($liCount == 0) { ?>
                        <th>
                            <ul style="list-style-type:none">
                    <?php } ?>
                                <li>
                                    <a href="<?= $block->escapeUrl($product['url']) ?>"><?= $block->escapeHtml($product['name']) ?></a>
                                </li>
                    <?php
                    $liCount++;
                    $i++;
                    if ($liCount == $ulLimit || $i == count($productsArray)) { ?>
                            </ul>
                        </th>
                        <?php $liCount = 0; ?>
                    <?php } ?>
                <?php }
                ?>
                </tr>
            </table>
        </div>
    <?php } ?>
</div>
