<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var \Magefan\HtmlSitemap\Block\Cms\Page $block
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
    <br>
    <?php foreach ($block->getCmsPagesList() as $page): ?>
        <a href="<?= $block->escapeUrl($block->getBaseUrl() . $page->getIdentifier()) ?>">
            <?= $block->escapeHtml($page['title']) ?>
        </a>
    <?php endforeach; ?>
    <?php if ($pages = $block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $pages ?></div>
    <?php endif ?>
</div>
