<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var \Magefan\HtmlSitemap\Block\Cms\Pages $block
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <div class="sitemap-item-wrap">
        <?php foreach ($block->getCmsPagesList() as $page): ?>
            <a class="sitemap-item" href="<?= $block->escapeUrl($block->getBaseUrl() . $page->getIdentifier()) ?>" title="<?= $block->escapeHtml($page['title']) ?>">
                <?= $block->escapeHtml($page['title']) ?>
            </a>
        <?php endforeach; ?>
    </div>
    <?php if ($pages = $block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $pages ?></div>
    <?php endif ?>
</div>
