<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Additional\Additional $block
 */

$links = $block->getLinksArray();
$limit = 4;
$i = 0;
$j = 0;
?>
<?php if (count($links)): ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <br>
        <?php foreach ($links as $link): ?>
            <?php if ($link): ?>
                <?= ($i === 0) ? '<div class="sitemap-col">' : '' ?>
                    <a href="<?= $block->escapeUrl($block->getBaseUrl() . $link['url'])?>" title="<?= $block->escapeHtml($link['title'])?>">
                        <?= $block->escapeHtml($link['title'])?>
                    </a>
                <?= ($i === $limit-1 || count($links)-1 == $j) ? '</div>' : '' ?>
                <?php
                    $i++;
                    $j++;

                    if ($i === $limit) {
                        $i = 0;
                    }
                ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($block->showViewMore()): ?>
            <a href="<?= $block->escapeUrl($block->getUrl('*/additional/links'))?>" style="color: red; padding: 5px;">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>
