<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Blog\Category $block
 */

$items = $block->getGroupedChildes();
?>
<?php if (count($items)) { ?>
    <div class="sitemap-item-type">
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <br />
        <div class="widget block block-categories" data-bind="scope: 'categories'">
            <ul class="accordion"  id="accordion-2">
                <?php
                $level = 0;
                $first = true;
                foreach ($items as $item) {
                    $newLevel = $item->getLevel();
                    if ($level == $newLevel && !$first) {
                         echo '</li>';
                    }
                    if ($level < $newLevel) {
                        echo '<ul>';
                    }
                    if ($level > $newLevel) {
                        for ($i = $level; $i > $newLevel; $i--) {
                            echo '</ul></li>';
                        }
                    } ?>
                    <li>
                    <a href="<?= $block->escapeUrl($item->getUrl()) ?>">
                        <?= $block->escapeHtml($block->escapeHtml($item->getTitle())) ?>
                    </a>
                    <?php
                    $level = $newLevel;
                    $first = false;
                } ?>
            </ul>
            <?php if ($block->showViewMore()): ?>
                <a href="<?= $block->escapeUrl($block->getUrl('*/blog_category/categories'))?>" style="color: red; padding: 5px;">
                    <?= $block->escapeHtml(__('View more'))?>
                </a>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>
