<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Catalog\Product $block
 */

$products = $block->getProductCollection();
?>

<?php if (count($products)) { ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2 class="sitemap-title"><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <div class="sitemap-item-wrap">
        <?php foreach ($products as $product): ?>
            <a class="sitemap-item" href="<?= $block->escapeUrl($product->getProductUrl()) ?>" title="<?=$block->escapeHtml($product->getName()) ?>">
                <?=$block->escapeHtml($product->getName()) ?>
            </a>
        <?php endforeach; ?>
        </div>
        <?php if ($block->showViewMore()): ?>
            <a class="view-more" href="<?= $block->escapeUrl($block->getUrl('*/catalog_product/products'))?>">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php } ?>
