<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Catalog\Category $block
 */

$items = $block->getGroupedChildes();
?>
<?php if (count($items)) { ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <br />
        <div class="widget block block-categories" data-bind="scope: 'categories'">
            <div class="accordion"  id="accordion-2">
                <?php
                $level = -1;
                $first = true;
                foreach ($items as $item) {
                    $newLevel = $item->getLevel();
                    if ($level == $newLevel && !$first) {
                        echo '</li>';
                    }
                    if ($level < $newLevel) {
                        echo '<ul>';
                    }
                    if ($level > $newLevel) {
                        for ($i = $level; $i > $newLevel; $i--) {
                            echo '</ul></li>';
                        }
                    } ?>
                    <li>
                        <a href="<?= $block->escapeUrl($item->getUrl()) ?>">
                            <?= $block->escapeHtml($item->getName()) ?>
                        </a>
                    <?php
                    $level = $newLevel;
                    $first = false;
                }

                $closedTags = ($level > 0) ? $level - 1 : 1;
                echo str_repeat('</li></ul>', $closedTags);
                ?>
            </div>
            <?php if ($block->showViewMore()): ?>
                <a href="<?= $block->escapeUrl($block->getUrl('*/catalog_category/categories'))?>" style="color: red; padding: 5px;">
                    <?= $block->escapeHtml(__('View more'))?>
                </a>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>
