<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Catalog\Product $block
 */

$products = $block->getProductCollection();
$limit = 4;
$i = 0;
$j = 0;
?>
<?php if (count($products)) { ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <br>
        <?php foreach ($products as $product): ?>
            <?= ($i === 0) ? '<div class="sitemap-col">' : '' ?>
            <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                <?=$block->escapeHtml($product->getName()) ?>
            </a>
            <?= ($i === $limit-1 || count($products)-1 == $j) ? '</div>' : '' ?>
            <?php
            $i++;
            $j++;

            if ($i === $limit) {
                $i = 0;
            }
            ?>
        <?php endforeach; ?>
        <?php if ($block->showViewMore()): ?>
            <a href="<?= $block->escapeUrl($block->getUrl('*/catalog_product/products'))?>" style="color: red; padding: 5px;">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php } ?>
