<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Cms\Page $block
 */

$pages = $block->getCmsPages();
?>
<?php if (count($pages)) { ?>
    <div>
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <br />
        <?php foreach ($pages as $page): ?>
            <a href="<?= $block->escapeUrl($block->getBaseUrl() . $page->getIdentifier()) ?>">
                <?= $block->escapeHtml($page['title']) ?>
            </a>
            <br/>
        <?php endforeach; ?>
        <?php if ($block->showViewMore()): ?>
            <a href="<?= $block->escapeUrl($block->getUrl('*/cms_page/page'))?>">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php } ?>
