<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>

<?php
/**
 * @var \Magefan\HtmlSitemap\Block\Cms\Page $block
 */

$pages = $block->getCmsPages();
?>

<?php if (count($pages)) { ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2 class="sitemap-title"><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <div class="sitemap-item-wrap">
        <?php foreach ($pages as $page): ?>
            <a class="sitemap-item" href="<?= $block->escapeUrl($block->getBaseUrl() . $page->getIdentifier()) ?>" title="<?= $block->escapeHtml($page['title']) ?>">
                <?= $block->escapeHtml($page['title']) ?>
            </a>
        <?php endforeach; ?>
        </div>
        <?php if ($block->showViewMore()): ?>
            <a class="view-more" href="<?= $block->escapeUrl($block->getUrl('*/cms_page/page'))?>" style="color: red; padding: 5px;">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php } ?>



